---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sensor-simulator.fullname" . }}-config
  namespace: {{ include "sensor-simulator.namespace" . }}
  labels:
    {{- include "sensor-simulator.labels" . | nindent 4 }}
data:
  field_sources.json: |
    {{- .Values.fieldConfig | toJson | nindent 4 }}
