---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: azure-iot-operations

resources:
  - ./base

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: ai-edge-inference
    path: patch-containers.yaml

images:
  - name: ai-edge-inference
    newTag: latest
