{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "mqtt-otel-trace-exporter.fullname" .) .Values.serviceAccount.name }}
  labels:
    {{- include "mqtt-otel-trace-exporter.labels" . | nindent 4 }}
  {{- if .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
  {{- end }}
{{- end }}
